In [2]:
#1)what is python library? why do we use it?


#A Python library is a collection of code and information that extends the capabilities 
#of the Python programming language. Libraries provide developers with a variety of tools 
#and modules to perform specific tasks more efficiently, without having to reinvent the wheel.


In [3]:
#2) what is the difference between numpoy array and list?  


#The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects.
#or example, a NumPy array of strings can only contain strings and no other data types, but a Python list can contain a
#mixture of strings, numbers, booleans and other objects.

In [4]:
#3) to find shape,size and dimension of following array



In [18]:
import numpy as npy

                                                             
arr2 = npy.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11, 12]])

print("shape of the array is", arr2.shape)
print("Size of the array: ", arr2.size)
print("Dimensions in are: ", arr2.ndim)
print(arr2)


shape of the array is (3, 4)
Size of the array:  12
Dimensions in are:  2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
#4) write the python code to acces the first row of the following array


#([[1,2,3,4],
#[5,6,7,8],
#[9,10,11, 12]])

In [25]:
import numpy as np

arr = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11, 12]])


print(arr[0])

[1 2 3 4]


In [26]:
#5) write the python code to acces the element at third row and fourth column of the following array



In [39]:
arr = np.array([[1,2,3,4], 
                 [5,6,7,8],
                 [9,10,11, 12]])


print(arr[: ,[2,3]])

[[ 3  4]
 [ 7  8]
 [11 12]]


In [36]:
#6) to extract all odd indexed elements in the given array



In [42]:
arr = np.array([[1,2,3,4], 
                 [5,6,7,8],
                 [9,10,11, 12]])


bool_arr = arr % 2 != 0
res = np.where(bool_arr)[0]
 
print("Indices list Odd elements is : ", res)

Indices list Odd elements is :  [0 0 1 1 2 2]


In [43]:
#7) to generate a random 3*3 matrix with values 0 and 1



In [50]:
import numpy as np 

array = np.random.randint(2, size=(3, 3)) 
print(array) 



[[1 1 1]
 [0 0 1]
 [1 0 1]]


In [51]:
#8) difference between np.random.rand and np.random.randn



In [52]:
#random. rand() produces random numbers from a uniform distribution over the interval [0, 1), 
# while np. random. randn() generates random numbers from a standard normal distribution.

In [53]:
#9) to increase the dimension of the following array  

#([[1,2,3,4],
#[5,6,7,8],
#[9,10,11, 12]])

In [16]:
import numpy as np 

x = np.array([[1,2,3,4], 
                 [5,6,7,8],
                 [9,10,11, 12]])



x.resize(5, 5) 

print(x) 



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


In [17]:
#10) to transpose the following array in numpy

#([[1,2,3,4], 
#[5,6,7,8],
#[9,10,11, 12]])


In [19]:
import numpy as np

x= np.array([[1,2,3,4], 
                 [5,6,7,8],
                 [9,10,11, 12]])

                                            # before transpose
print(x, end ='\n\n')

                                            # after transpose
print(x.transpose())


                                             


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [20]:
#11) the following matrix: A=[1,2,3,4][5,6,7,8][9,10,11,12]]    B=[[1,2,3,4][5,6,7,8][9,10,11,12]]



In [21]:
# index wise multiplication


In [23]:
import numpy as np


in_arr1=np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 
in_arr2 = np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 
	
print ("1st Input array : ", in_arr1) 
print ("2nd Input array : ", in_arr2) 

out_arr=np.array(in_arr1)*np.array(in_arr2) 
print ("Resultant output array: ", out_arr) 


1st Input array :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2nd Input array :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Resultant output array:  [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [24]:
# matrix multiplication



In [37]:
import numpy as np

mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])

res = np.dot(mat1,mat2)

print(res)


[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


In [33]:
# add both matrices



In [34]:
import numpy as np
 
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

result = np.array(X) + np.array(Y)

print(result)


[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [38]:
# subtrarct matrix B from A



In [40]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

print("subtraction of two matrix")
print(np.subtract(A, B))


Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [41]:
# divide matrix b by a



In [43]:
import numpy as np 

arr1 = [2, 27, 2, 21, 23] 
arr2 = [2, 3, 4, 5, 6] 
print ("arr1		 : ", arr1) 
print ("arr2		 : ", arr2) 

out = np.divide(arr1, arr2) 
print ("\nOutput array : \n", out) 


arr1		 :  [2, 27, 2, 21, 23]
arr2		 :  [2, 3, 4, 5, 6]

Output array : 
 [1.         9.         0.5        4.2        3.83333333]


In [44]:
#12) which function in  numpy can be used to swap the byte order of an array?


In [45]:
 
# byteswap() function 
import numpy as np


                                                      # a is an array of integers. 
a = np.array([1, 256, 100], dtype = np.int16) 

print(a.byteswap(True)) 


[  256     1 25600]


In [46]:
#13) significance of np.linalg.inv function



In [47]:
# the function is used to calculate the inverse of a matrix

import numpy as np

A = np.array([[6, 1, 1],
			[4, -2, 5],
			[2, 8, 7]])

                              # Calculating the inverse of the matrix
print(np.linalg.inv(A))


[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [48]:
#14) what does the np.reshape do?



In [50]:
# the np.reshape() function changes the shape of the array without changing the data.

import numpy as np 
	
x= np.array([1, 2, 3, 4, 5, 6]) 
print("Original array:") 
display(x) 

                                        # using reshape() 
print("Changed array") 
display(x.reshape(2, 3)) 	


Original array:


array([1, 2, 3, 4, 5, 6])

Changed array


array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
#15) what is broadcasting in  numpy



In [52]:
# The term broadcasting refers to the ability of NumPy to treat arrays with different dimensions during arithmetic
# operations. This process involves certain rules that allow the smaller array to be ‘broadcast’ across the larger one, 
# ensuring that they have compatible shapes for these operations.

import numpy as np 
A = np.array([[11, 22, 33], [10, 20, 30]]) 
print(A) 

b = 4
print(b) 

C = A + b 
print(C)


[[11 22 33]
 [10 20 30]]
4
[[15 26 37]
 [14 24 34]]
